version: '3'

services:
    googleOAuth2Interface:
        build: ./GoogleOAuth2Interface
    ports:
      - 5001:5001
    
    telegramInterface:
        build: ./TelegramInterface
        depends_on:
            - googleOAuth2Interface
    
    businessLogic:
        build: ./BusinessLogic
        depends_on:
            - googleOAuth2Interface
            - telegramInterface